AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition

Resources:

  ApiGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambda_function.lambda_handler
      Runtime: python3.8
      Events:
        ApiEvent:
          Type: HttpApi


# CounterTable:
#   Type: AWS::Serverless::SimpleTable
#   Properties:
#     TableName: resume_serverless_counter
#     Primary Key:


